apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops
    spec:
      containers:
      - image: manrala/numeric-app:bdcb881fa5099eabf3b39dbb68699f0591d9177d
        name: numeric-app
        ports:
        - containerPort: 8080
