apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops
    spec:
      containers:
      - image: manrala/numeric-app:8605e5b17d81f215ac31a8a1bb19161ae99028f7
        name: numeric-app
        ports:
        - containerPort: 8080
