apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops
    spec:
      containers:
      - image: manrala/numeric-app:2403d46a5d4b718d028fa1cfec2dbcb527e7f2ad
        name: numeric-app
        ports:
        - containerPort: 8080
