apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops
    spec:
      containers:
      - image: manrala/numeric-app:21b6ea66abef828037630f7f6ffa62489883b5f2
        name: numeric-app
        ports:
        - containerPort: 8080
