apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devsecops
    spec:
      containers:
      - image: manrala/numeric-app:1488bd53da4cf9409425080e654eb570c6d333fc
        name: numeric-app
        ports:
        - containerPort: 8080
