apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  ports:
  - name: devsecops
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30906
  selector:
    app: devsecops
  type: NodePort
